### PR TITLE
issue #8 added red panda favicon

### PR DESCRIPTION
**Pull request by Kornil**
I've made it on http://www.favicon.cc/ it's free to use for whatever you want

### CODE REVIEW

**Review by JacksonBates — CHANGES_REQUESTED** [review]
I really like it, but to close the issue I'd like to actually put the favicon into the code.

Are you able to make a 310x310 px version and run it through http://www.favicomatic.com/ ?

Then use the code that generates in the index.html file in the public folder.

This will not only give us a nice favicon, but a great looking mobile icon, among others!

**Comment by JacksonBates** [comment]
I noticed that the icon designer you used doesn't let you make a 310 version.

I played with it in Gimp, and managed to get a decent 310 version out of it:

red-panda

Would you like to try to get that into the code?

**Comment by Kornil** [comment]
i made a new HD version and I have the new code from http://www.favicomatic.com/ I dont know how to commit on this pull request tho, do I need to make another one?

**Comment by JacksonBates** [comment]
Hmm, not sure. Try committing to the branch you've already PR'd?

**Comment by Kornil** [comment]
Added all the favicons!

**Comment by Kornil** [comment]
And you are right! I just pushed another commit to center the images(they were sightly on the left), see you tomorrow!

**Review by JacksonBates — APPROVED** [review]
LOVE IT!

**Comment by JacksonBates** [comment]
Hey @Kornil, can you confirm that just adding to the branch you'd already PR'd was all you needed to do? Or are there other steps?

**Comment by Kornil** [comment]
@JacksonBates it works now, basically once you have the image to run on http://www.favicomatic.com/ you just copy the code on index.html and place the images in your preferred folder(change the path on links and meta to link that folder) BUT:


favicon.ico needs to be in root folder(I placed it with index.html it works perfectly) and you dont need code in index.html for it.


http://www.favicomatic.com/favicon-test to test how it works


P.S. if it doesn't show the new favicon right away you have to go to http://pairboard.surge.sh/favicon.ico let it load then clear the browser cache, close the browser and open it again.

**Comment by JacksonBates** [comment]
@Kornil I got it working just fine. I meant, was committing to the same branch you'd already PR'd was enough to amend the PR?

**Comment by Kornil** [comment]
I commited on the same branch I created and then went to pull request it again, github magic updated this pr instead of creating a new one

**Comment by JacksonBates** [comment]
Good to know - next time someone asks, I can answer confidently!

**Pull request merged**
