### PR TITLE
Write introduction in first pr club

### PR DESCRIPTION
**Pull request by kevcomedia**

### CODE REVIEW

**Comment by JacksonBates** [comment]
? Why the closed PR, Kev?

**Comment by kevcomedia** [comment]
Oh my. I think I deleted the branch too soon. My bad 😔

**Review by JacksonBates — CHANGES_REQUESTED** [review]
Your version of the repo is behind the original master branch, so there is a merge conflict.

I can fix it manually, but first I'd like to see if you can fix it by syncing your repo and re-committing to your branch the PR is on.

If there are no merge conflicts on your end, I can accept the PR with the click of a button :)

There are details about how to keep in sync in the contributing.md

**Comment by kevcomedia** [comment]
Hmmm... I'll try opening a new PR.

**Pull request closed without merging**
