### PR TITLE
Issue #78 User card alignment / responsivness

### PR DESCRIPTION
**Pull request by MARKJ78**
Changed inner container from bootstrap row to flexbox (.inner-container)

Changed user-cards, removed bootstrap col classes to use flexbox to flex  and center correctly within .inner-container

User cards look and behave like this http://codepen.io/mpjones/pen/ENpazx?editors=1000.

Also tidied up the CSS formatting a bit, hence a lot of red in the compared. Actual CSS changes are only lines 87 to 109 inclusive on the green side, and 87 to 96 on the red side. .

### CODE REVIEW

**Review by JacksonBates — CHANGES_REQUESTED** [review]
On desktop, the cards should still be listed in two columns rather than one. I'm seeing this at the moment:
image

Also, I think your text editor has inserted an extra two spaces for ever indentation? Some text editor linters do that automatically I think. The rest of the codebase sticks to 2 spaces for indentation - could you revert it to that?

**Comment by MARKJ78** [comment]
Did you implement the changes in App.css, CamperCard.js & CamperList.js? Because I only see one file in the view changes button above.

image

There is a custom break point on the cards of 1024px - this is the point they should break into 2 columns. If they are not it suggests the 2 js files were not merged - as they hold the html with new classes. Without those the breaks won't work. 

Adjusted the spaces in my editor too to match the project.

**Comment by JacksonBates** [comment]
Hmmm....I'll try it again - I may have been on the wrong branch without realising

**Comment by MARKJ78** [comment]
I have just pushed changes to my master branch. (indentation of css). Are those indentation changes visible to this pull request?

**Comment by JacksonBates** [comment]
It may also be because I manually had to handle a merge conflict, and I may have missed something important...

**Comment by MARKJ78** [comment]
As long as you have 

 ` <div className='user-card'>`  Ln42 in CamperCard.js
`<div className='container'>` Ln6 in CamperList.js

and the css changes on the lines mentioned in the original note - then that's all the cards needed :)

**Comment by MARKJ78** [comment]
Hang on a minute. Stop.

looks like something has reverted.

**Comment by MARKJ78** [comment]
There we go,

`<div className='inner-container'>`Ln 7 in CamperList had been reverted back to a "row".

Changed back to what it should have been.

**Comment by JacksonBates** [comment]
Took me longer than anticipated to roll out my own websockets update (I forgot to save the npm package!)

I'll check this in the morning :)

**Pull request merged**
